/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.institute_management.payment_mgt;

import com.institute_management.course_mgt.CourseDbConnection;
import com.institute_management.course_mgt.courseBean;
import com.institute_management.course_mgt.selectCourse;
import static com.institute_management.course_mgt.test.oneTimeStudentID;
import com.institute_management.util.autoSuggest;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author Malinda Ranabahu
 */
public class PaymentDashBoard extends javax.swing.JFrame {

    NewPaymentDbConnection conn = new com.institute_management.payment_mgt.NewPaymentDbConnection();
    public static paymentBean pb = new paymentBean();

    public PaymentDashBoard() {
        initComponents();

        //Auto Suggest
        final JTextField textfieldID = (JTextField) cmbStdIDReg.getEditor().getEditorComponent();
        final JTextField textfieldName = (JTextField) cmbStdNameReg.getEditor().getEditorComponent();
        final JTextField textfieldNIC = (JTextField) cmbStdNICReg.getEditor().getEditorComponent();
        final JTextField textfieldMobile = (JTextField) cmbStdMobReg.getEditor().getEditorComponent();

        textfieldID.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent ke) {
                SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        new autoSuggest().comboFilter(textfieldID.getText(), cmbStdIDReg, 1);
                    }
                });
            }
        });

        textfieldName.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent ke) {
                SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        new autoSuggest().comboFilter(textfieldName.getText(), cmbStdNameReg, 2);
                    }
                });
            }
        });
        textfieldNIC.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent ke) {
                SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        new autoSuggest().comboFilter(textfieldNIC.getText(), cmbStdNameReg, 3);
                    }
                });
            }
        });
        textfieldMobile.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent ke) {
                SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        new autoSuggest().comboFilter(textfieldMobile.getText(), cmbStdNameReg, 4);
                    }
                });
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbCourseID = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        lblCourse = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        lblStudentName = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        lblPayment = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        lblcardType = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        lblLecturerName = new javax.swing.JLabel();
        lblThirdMonth = new javax.swing.JLabel();
        lblSecondMonth = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmbStdIDReg = new javax.swing.JComboBox();
        cmbStdNICReg = new javax.swing.JComboBox();
        jLabel48 = new javax.swing.JLabel();
        cmbStdNameReg = new javax.swing.JComboBox();
        cmbStdMobReg = new javax.swing.JComboBox();
        jLabel49 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        lblvrification = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        lblFirstMonth = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Payment Details"));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel2.setText("Select Course");

        cmbCourseID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbCourseIDMouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 204));
        jButton2.setText("Check Payments");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel47.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel47.setText("Course");

        lblCourse.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        jLabel40.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel40.setText("Course Description");

        lblDescription.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        jLabel39.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel39.setText("Student Name");

        lblStudentName.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        jLabel46.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel46.setText("Payment Amount");

        lblPayment.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        jLabel45.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel45.setText("Card Type");

        lblcardType.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        jLabel42.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel42.setText("last two Payment Status");

        jLabel41.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel41.setText("Lecturer Name");

        lblLecturerName.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        lblThirdMonth.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        lblSecondMonth.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setText("Make Payment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 204));
        jButton3.setText("Advanced Options");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Reg ID");

        cmbStdIDReg.setEditable(true);
        cmbStdIDReg.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        cmbStdIDReg.setForeground(new java.awt.Color(0, 102, 255));
        cmbStdIDReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbStdIDRegMouseClicked(evt);
            }
        });
        cmbStdIDReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbStdIDRegKeyPressed(evt);
            }
        });

        cmbStdNICReg.setEditable(true);
        cmbStdNICReg.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        cmbStdNICReg.setForeground(new java.awt.Color(0, 102, 255));
        cmbStdNICReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbStdNICRegMouseClicked(evt);
            }
        });

        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel48.setText("NIC");

        cmbStdNameReg.setEditable(true);
        cmbStdNameReg.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        cmbStdNameReg.setForeground(new java.awt.Color(0, 102, 255));
        cmbStdNameReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbStdNameRegMouseClicked(evt);
            }
        });
        cmbStdNameReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStdNameRegActionPerformed(evt);
            }
        });

        cmbStdMobReg.setEditable(true);
        cmbStdMobReg.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        cmbStdMobReg.setForeground(new java.awt.Color(0, 102, 255));
        cmbStdMobReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbStdMobRegMouseClicked(evt);
            }
        });

        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel49.setText("Mobile");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jButton10.setText("Clear");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("Name");

        jLabel57.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 0, 255));
        jLabel57.setText("Student Varification Status");

        lblvrification.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblvrification.setForeground(new java.awt.Color(0, 0, 255));

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(0, 0, 255));
        jLabel58.setText(":");

        lblFirstMonth.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(cmbStdIDReg, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177)
                        .addComponent(cmbStdNameReg, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(cmbStdMobReg, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(383, 383, 383)
                        .addComponent(jButton2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(547, 547, 547)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(655, 655, 655)
                        .addComponent(btnSearch))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(cmbStdNICReg, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(lblvrification, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(lblPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(738, 738, 738)
                        .addComponent(jButton10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel57))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(cmbCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(lblcardType, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(jLabel40))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(148, 148, 148)
                                    .addComponent(lblCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(148, 148, 148)
                                    .addComponent(lblStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(148, 148, 148)
                                    .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(107, 107, 107)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel42)
                                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(154, 154, 154)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblSecondMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblLecturerName, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblThirdMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblFirstMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(679, 679, 679)
                            .addComponent(jButton3))))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(lblvrification, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(lblPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel58))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel27))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(lblcardType, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(lblStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbStdIDReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbStdNameReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel49))
                            .addComponent(cmbStdMobReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(134, 134, 134)
                        .addComponent(jLabel47))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel48))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jLabel46))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(cmbStdNICReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jLabel45))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel39))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel40))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(cmbCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(jButton2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(btnSearch))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jButton10)))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLecturerName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel41)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblThirdMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel42)
                                                .addGap(10, 10, 10)
                                                .addComponent(lblSecondMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblFirstMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jButton3)))
                            .addComponent(lblCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            boolean studentExistancy = new com.institute_management.course_mgt.CourseDbConnection().checkstudentExistancy(cmbStdIDReg.getEditor().getItem().toString());
            //check paymenttable
            if (studentExistancy) {

                pb.setCourseID(cmbCourseID.getSelectedItem().toString());
                pb.setS_id(cmbStdIDReg.getEditor().getItem().toString());
                pb.setAmount(conn.getCourseFee(cmbCourseID.getSelectedItem().toString()));

                LinkedHashMap<String, String> paymentMap = conn.getPaymentDetails(cmbCourseID.getSelectedItem().toString(), cmbStdIDReg.getEditor().getItem().toString(), 6);
                int count = 0;
                for (Map.Entry<String, String> entry : paymentMap.entrySet()) {
                    String value = entry.getValue().toString();
                    String key = entry.getKey().toString();

                    if (count == 2) {
                        lblThirdMonth.setForeground(new java.awt.Color(0,153,51));
                        if (value.contains("not")) {
                            lblThirdMonth.setForeground(new java.awt.Color(255, 0, 0));
                        }
                        lblThirdMonth.setText(key + "  :   " + value);
                    } else if (count == 1) {
                        lblSecondMonth.setForeground(new java.awt.Color(0,153,51));
                        if (value.contains("not")) {
                            lblSecondMonth.setForeground(new java.awt.Color(255, 0, 0));
                        }
                        lblSecondMonth.setText(key + "  :   " + value);
                    } else if (count == 0) {
                        lblFirstMonth.setForeground(new java.awt.Color(0,153,51));
                        if (value.contains("not")) {
                            lblFirstMonth.setForeground(new java.awt.Color(255, 0, 0));
                        }
                        lblFirstMonth.setText(key + "  :   " + value);
                    }
                    count++;
                }
                String aa[] = new com.institute_management.course_mgt.CourseDbConnection().getStudentData(cmbStdIDReg.getEditor().getItem().toString(), cmbCourseID.getSelectedItem().toString());
                lblStudentName.setText(aa[0]);
                lblcardType.setText(aa[1]);
                courseBean x = new com.institute_management.course_mgt.CourseDbConnection().getCourseDetails(cmbCourseID.getSelectedItem().toString());
                selectCourse.OnlyForCourseEditBean = x;
                lblCourse.setText(cmbCourseID.getSelectedItem().toString());
                lblLecturerName.setText(x.getLecturerName());
                lblPayment.setText(Double.toString(x.getMonthlyFee()));

            } else {
                JOptionPane.showMessageDialog(new JFrame(), "There is no such ID.Please check the number");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(new JFrame(), "error");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbCourseIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbCourseIDMouseClicked

    }//GEN-LAST:event_cmbCourseIDMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            HashMap<String, Integer> successStatus = new HashMap<String, Integer>();
            ArrayList<String> months = new ArrayList<String>();

            Calendar cal = Calendar.getInstance();
            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            String currentDate = dateFormat.format(cal.getTime());
            String curMonth = (new SimpleDateFormat("MMMM").format(cal.getTime())).toLowerCase();
            String curYear = (new SimpleDateFormat("yyyy").format(cal.getTime())).toLowerCase();
            months.add(curMonth);
            int paymentAmount = conn.getCourseFee(cmbCourseID.getSelectedItem().toString());
            pb.setAmount(paymentAmount);
            pb.setCourseID(cmbCourseID.getSelectedItem().toString());
            pb.setDate(currentDate);
            pb.setMonth(months);
            pb.setS_id(cmbStdIDReg.getEditor().getItem().toString());
            pb.setYear(curYear);
            successStatus = conn.makePayment(pb);
            String errorMsg = "";
            for (Map.Entry<String, Integer> entry : successStatus.entrySet()) {
                int value = (Integer) entry.getValue().intValue();
                String key = entry.getKey();
                if (value != 1) {
                    errorMsg = errorMsg + "," + key;
                }
            }

            if (errorMsg.equals("")) {
                JOptionPane.showMessageDialog(new JFrame(), "Successfully Inserted");
            } else {
                JOptionPane.showMessageDialog(new JFrame(), "Fail Make payment for following Months(" + errorMsg + ").Try again");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(new JFrame(), "error");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        oneTimeStudentID = cmbStdIDReg.getEditor().getItem().toString();
        paymentPOPUP ppu = new paymentPOPUP();
        ppu.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cmbStdIDRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbStdIDRegMouseClicked

    }//GEN-LAST:event_cmbStdIDRegMouseClicked

    private void cmbStdIDRegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbStdIDRegKeyPressed

    }//GEN-LAST:event_cmbStdIDRegKeyPressed

    private void cmbStdNICRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbStdNICRegMouseClicked

    }//GEN-LAST:event_cmbStdNICRegMouseClicked

    private void cmbStdNameRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbStdNameRegMouseClicked

    }//GEN-LAST:event_cmbStdNameRegMouseClicked

    private void cmbStdNameRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStdNameRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStdNameRegActionPerformed

    private void cmbStdMobRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbStdMobRegMouseClicked

    }//GEN-LAST:event_cmbStdMobRegMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String id = cmbStdIDReg.getEditor().getItem().toString();
        String name = cmbStdNameReg.getEditor().getItem().toString();
        String nic = cmbStdNICReg.getEditor().getItem().toString();
        String mob = cmbStdMobReg.getEditor().getItem().toString();

        HashMap temp = new HashMap();
        try {
            temp = new CourseDbConnection().SearchStudent(id, name, nic, mob);
            if (temp.size() > 0) {
                cmbStdIDReg.setSelectedItem(temp.get("regID"));
                cmbStdNameReg.setSelectedItem(temp.get("name"));
                cmbStdNICReg.setSelectedItem(temp.get("nic"));
                cmbStdMobReg.setSelectedItem(temp.get("mobile"));
                lblvrification.setText("Verify");
            } else {
                cmbStdIDReg.setSelectedItem("");
                cmbStdNameReg.setSelectedItem("");
                cmbStdNICReg.setSelectedItem("");
                cmbStdMobReg.setSelectedItem("");
                lblvrification.setForeground(new java.awt.Color(0, 153, 51));
                lblvrification.setText("Wrong Entry");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), "No Match Found");

        }

        cmbCourseID.removeAllItems();
        PreparedStatement stmt = null;
        ResultSet result = null;

        try {
            String query = "SELECT `course_id` FROM `student-course` where s_id like '%" + cmbStdIDReg.getEditor().getItem().toString() + "%'";

            stmt = new com.institute_management.payment_mgt.PaymentDbConnection().getConnection().prepareStatement(query);

            result = stmt.executeQuery();

            while (result.next()) {
                String couseID = result.getString("course_id");
                cmbCourseID.addItem(couseID);
            }

            result.close();
            stmt.close();

        } catch (Exception ex) {

        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        cmbStdIDReg.setSelectedItem("");
        cmbStdNameReg.setSelectedItem("");
        cmbStdNICReg.setSelectedItem("");
        cmbStdMobReg.setSelectedItem("");
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox cmbCourseID;
    private javax.swing.JComboBox cmbStdIDReg;
    private javax.swing.JComboBox cmbStdMobReg;
    private javax.swing.JComboBox cmbStdNICReg;
    private javax.swing.JComboBox cmbStdNameReg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblFirstMonth;
    private javax.swing.JLabel lblLecturerName;
    private javax.swing.JLabel lblPayment;
    private javax.swing.JLabel lblSecondMonth;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblThirdMonth;
    private javax.swing.JLabel lblcardType;
    private static javax.swing.JLabel lblvrification;
    // End of variables declaration//GEN-END:variables
}
